# Generated by Django 4.1.1 on 2022-09-09 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_remove_userprofile_bio"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="profile_pic",
            field=models.URLField(blank=True),
        ),
    ]
