# Generated by Django 4.1.1 on 2022-09-09 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_alter_userprofile_profile_pic"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="profile_pic",
        ),
        migrations.AddField(
            model_name="userprofile",
            name="image",
            field=models.URLField(
                blank=True,
                default="https://cdn.pixabay.com/photo/2015/10/05/22/37/blank-profile-picture-973460_1280.png",
            ),
        ),
    ]
