# Generated by Django 4.1.1 on 2022-09-09 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_alter_userprofile_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="image",
            field=models.ImageField(default="default.webp", upload_to="profile_pics"),
        ),
    ]
