# Generated by Django 4.1.1 on 2022-09-10 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="image",
            field=models.ImageField(
                default="ddefault.webp", upload_to="user_directory_path"
            ),
        ),
    ]
