# Generated by Django 4.1.1 on 2022-09-10 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_post_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="image",
            field=models.ImageField(
                default="default.webp", upload_to="user_directory_path"
            ),
        ),
    ]
