# Generated by Django 4.1.1 on 2022-09-10 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0004_alter_post_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="image",
            field=models.ImageField(
                default="blog_default.png", upload_to="profile_pics"
            ),
        ),
    ]
