# Generated by Django 4.1.1 on 2022-09-10 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0005_alter_post_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="blog_view",
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
