# Generated by Django 4.1.1 on 2022-09-10 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0006_post_blog_view"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="image",
            field=models.ImageField(
                blank=True,
                default="blog_default.png",
                null=True,
                upload_to="user_directory_path",
            ),
        ),
    ]
