# Generated by Django 4.1.1 on 2022-09-12 11:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("blog", "0010_rename_body_comment_content"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="likes",
            field=models.ManyToManyField(
                blank=True, related_name="collected_votes", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
