# Generated by Django 4.1.1 on 2022-09-12 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0012_remove_comment_name_comment_user_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="blog_comment",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
