# Generated by Django 4.1.1 on 2022-09-13 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0015_alter_comment_content"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="image",
            field=models.ImageField(
                default="blog_default.png", upload_to="user_directory_path"
            ),
        ),
    ]
